### ISSUE TITLE
Add support for forwarding TCP/UDP streams

### ISSUE THREAD

**Issue by fpragana** [hassio-addons/addon-nginx-proxy-manager#24]
Please, 
add support for forwarding TCP/UDP streams.

**Comment by frenck** [comment]
I've had this discussion many many times with a couple of people.
Please provide me 1 valid use-case for Hass.io that can justify re-enabling this and dropping the add-on into the host network (and its implications).

**Comment by fpragana** [comment]
All features related with automation and entreteriment is centered in my hassio.
My tvbox provide app to stream content in udp connection.

**Comment by frenck** [comment]
Could you explain it a little more extensive, since I don't get what the proxy manager adds in this case...

**Comment by fpragana** [comment]
For redirect connection outside my home for tvbox..the intent is:

**Comment by frenck** [comment]
Well.. the thing is, in order to use the nginx proxy manager with UDP, you'd have to forward a specific port to the add-on, which then will proxy UDP traffic to the service. 

Why not forward the port to the service in that case directly?

Please remember, UDP forwarding does not support "virtual" hosts, a dedicated port has to be created on the add-on and in your forwarding router, for each of your streams, to be able to work.

**Comment by fpragana** [comment]
For redirect connection outside my home for tvbox..the intent is:
Config my mobile app with http:\\myhouse.dyndnd.org
My router receive the connection and transfer to nginx
The nginx receive and check host to redirect for correct tvbox udp connection.
I have 3 tv Box, the app dont allow configure Port..

**Comment by frenck** [comment]
You can't check the host....

It is UDP traffic!

**Comment by frenck** [comment]
Closing this issue, since:
A) This is not going to work in your case, even if the add-on added it.
B) Since it is a not working and valid use-case, I'm not adding it in.
