### ISSUE TITLE
OVH DNS Challenge does not work - Seems to be Certbot and Python versions issue

### ISSUE THREAD

**Issue by pmorange** [hassio-addons/addon-nginx-proxy-manager#277]
# Problem/Motivation
I can request a certificate for a single subdomain, but a wildcard certificate cannot be issued : DNS challenge fails with a Python error.

## Expected behavior
The certificate is issued by letsencrypt without error.

## Actual behavior
The following error is thrown by Python :
```
Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
An unexpected error occurred:
TypeError: create_record() got an unexpected keyword argument 'type'
Please see the logfiles in /var/log/letsencrypt for more details.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

## Steps to reproduce
Try to add a new Certificate : select OVH (I guess others will have the problem too), DNS challenge.

## Proposed changes
The following commit could be the solution but I haven't tried it yet : 
https://github.com/mikesplain/addon-nginx-proxy-manager/commit/5730f50795aa6ff0f67d4b542dc4206d039b0acc
The problem is also explained here :
https://stackoverflow.com/questions/67536198/got-an-error-while-trying-to-create-ssl-certificate-on-ovh-vps-server

This is a code problem probably due to a Python upgrade with the code of this component not being updated.

**Comment by pmorange** [comment]
Upgrading to the latest version of Certbot should do the trick, as the code is now correct :
![image](https://user-images.githubusercontent.com/8950440/133570495-ebf83b49-1685-4a43-b481-99040ba50a3c.png)

The problem has been corrected in Certbot in may, with this commit :
https://github.com/certbot/certbot/commit/bc23e07ee5c144aa9b1d5cf9e0ba303d9e91a695

**Comment by alafon** [comment]
Confirming the issue and that the solution provided by @pmorange  should work

**Comment by eroldan** [comment]
Yep. Linode DNS challenge broken with same error.

**Comment by mlocher** [comment]
as is DNSimple

**Comment by mniewiera** [comment]
i also have the same problem with dns challenge with OVH

**Comment by jaytea33** [comment]
> i also have the same problem with dns challenge with OVH. Does anyone know how to implement the suggested solution from @pmorange ? I have no idea how to access the docker container in home assistant. In a regular docker environment i would know how...

You can get to the container 1 of 2 ways - either launching bash on the NGINX Proxy Manager container within Portainer OR SSHing to your HA instance via Putty (install the better SSH add-on if you haven't already, not the one that's named nearly identical to get more access to your HA instance) then run the following commands to enter bash directly on the NGINX Proxy Manager container:

docker exec -it addon_a0d7b954_nginxproxymanager bash

pip install -U certbot

Doing so updated certbot from 1.11 to 1.22 but due to the way Docker works, rebooting NGINX Proxy Manager undoes the changes. The only ways I could think to make it permanent would be to somehow write to persistent storage in the docker image or spin up a new Docker container - using Portainer would probably be easier.

**Comment by eroldan** [comment]
Made a PR with the fix. If somebody is interested in testing it a repository is available to use as described here https://www.home-assistant.io/common-tasks/os#installing-third-party-add-ons

REPO: https://github.com/eroldan/addon-nginx-proxy-manager

PR: https://github.com/hassio-addons/addon-nginx-proxy-manager/pull/315
