### ISSUE TITLE
Reverse proxy multiple domains

### ISSUE THREAD

**Issue by kingb2019** [hassio-addons/addon-nginx-proxy-manager#320]
# Problem/Motivation

>Not able to get a second domain forwarded via reverse proxy. Got the first domain, with subdomains working great. Added 2nd and it has never worked for me. Reset the add-on and HA various times. Logs do not reflect the 2nd domain at all.

## Expected behavior

> Forward requests as designed.

## Actual behavior

> Forwards requests only for the 1st domain added.

## Steps to reproduce

> Setup 1st domain and sub domains, test - should pass. Add second domain, test - will fail (in my case).

**Comment by TUNER88** [comment]
Issue is still there since no new version was released so far.

**Comment by D-side** [comment]
I have a working multi-domain setup based on this addon, probably many do, so this issue **as described** generally does not happen…

> has never worked for me

@kingb2019 can you clarify that part? What exactly happens when you visit that second domain in your browser?
If there's no record in the logs at all, I would suspect that the second domain name just isn't configured to point at the same server in DNS. The browser's error page should be able to provide some details.
