### ISSUE TITLE
Addon does not start

### ISSUE THREAD

**Issue by olskar** [hassio-addons/addon-nginx-proxy-manager#322]
# Problem/Motivation
The addon does not start

For some reason the addon does not start. Cant see anything obvious in the logs?

```
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Ubuntu 20.04.4 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 2022.2.9
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] npm.sh: executing... 
ln: /var/tmp/nginx/nginx: File exists
[cont-init.d] npm.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
      
m
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Ubuntu 20.04.4 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 2022.2.9
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] npm.sh: executing... 
ln: /var/tmp/nginx/nginx: File exists
[cont-init.d] npm.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
      
m
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by tykeal** [comment]
I recently did a new build of HA and ran into this as well. As I had just installed the MariaDB addon I figured that perhaps something wasn't fully configured correctly. I gave my HA system (not just HA itself) a reboot and it came up with that problem again, but then corrected itself after trying a few times (I had watchdog enabled so it would keep trying to start)

**Comment by olskar** [comment]
This issue is still not solved FYI

**Comment by sinclairpaul** [comment]
Are you able to duplicate this on a supported system?

>  System: Ubuntu 20.04.4 LTS  (amd64 / qemux86-64)

**Comment by Vector-Int13** [comment]
@frenck 

To say a few nice words here, the Nginx Proxy Manager plugin works really well. It's a piece of decent work.

The only thing I would have as a comment is that the documentation doesn't mention Maria DB as a prerequest. 
The plugin does not perform a check when installed. The quickest way is to remove the plugin, install MariaDB plugin , set the password and start it and install the Mgix plugin again. 
Then it works perfectly. I would just like it to be able to reply on multiple https ports.


I have to appreciate that it doesn't contain a config error like the original plugin "Let's Encrypt". Where the GUI config misspells the domain list and leaves -null in there.


Thank you very much for this work.

**Comment by Vector-Int13** [comment]
> This issue is still not solved FYI

Care should be taken that neither the Lets Encrypt plugin nor the "NGINX Home Assistant SSL proxy" plugin has been installed before, as there may be conflicting configuration files or ports.
This plugin installs the necessary files and prerequests  except MariaDB itself.

Conflict of configuration files or already occupied ports may occur.
The easiest way is to remove the plugins. Remove the configuration files from the Lets Encrypt and NGINX directories. Then check the MariaDB function. 
- database: homeassistant
  username: homeassistant

Then reinstall Nginx Proxy Manager.

You can of course verify all configuration files, permissions and ports used, but I think that's a longer way to get the same result.

Unfortunately I don't have Ubuntu and even if I did, I wouldn't have the same set of add-ons in the same order as you. That's why a specific simple solution can't be found for you.

**Comment by frenck** [comment]
> The only thing I would have as a comment is that the documentation doesn't mention Maria DB as a prerequest.

It does. First step in the documentation even:

![image](https://user-images.githubusercontent.com/195327/173304649-e7985f95-1962-454b-8ae1-b3b87dd2b267.png)

> The plugin does not perform a check when installed. 

It does.

https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/38ea91c279331038880d4ece3d40cff614839c8a/proxy-manager/rootfs/etc/cont-init.d/mysql.sh#L11-L17

> The quickest way is to remove the plugin, install MariaDB plugin , set the password and start it and install the Mgix plugin again.

That statement is incorrect; Please don't mix up the terms add-ons and plugins. Secondly, you don't need to remove this add-on and install MariaDB first. Just add MariaDB; no need to uninstall anything.

> I have to appreciate that it doesn't contain a config error like the original plugin "Let's Encrypt". Where the GUI config misspells the domain list and leaves -null in there.

There is no field to fill in; nor is this in scope for an add-on to control.

> Care should be taken that neither the Lets Encrypt plugin nor the "NGINX Home Assistant SSL proxy" plugin has been installed before, as there may be conflicting configuration files or ports.

> The easiest way is to remove the plugins.

This is not correct advise. You don't need to remove anything. Please just use the control provided in the addon settings.

---

Anyways, most of your comments are not related to anything with the issue either; so I'm not sure how you ended up here or how they relate to the OP. 🤷

**Comment by frenck** [comment]
This issue is caused by: ` System: Ubuntu 20.04.4 LTS  (amd64 / qemux86-64)`

That is not a supported system (only Debian is supported, not Ubuntu) by Home Assistant.
Please use a supported system.

../Frenck

**Comment by Vector-Int13** [comment]
> That statement is incorrect; Please don't mix up the terms add-ons and plugins. Secondly, you don't need to remove this add-on and install MariaDB first. Just add MariaDB; no need to uninstall anything.


I'm not surprised you don't understand most of what I write.
I'm just not sure why.

Yes, the documentation already lists MariaDB as a prerequest.
I probably looked wrong, or a long time ago. I apologize.
The add-on checks to see if MariaDB is there. But after you start it.
Admittedly, it says so quite clearly in the log.

What I claim and insist,that is the easiest way in such a case ( and I have tried it), is to remove the addon, install MariaDB, check if it is running and then reinstall the addon.
It's 100% tried and tested. 
If I mix addon and plug-in it's a translation error. Take it up with whoever translates the thing into czech.
Can you describe what you understand by what term. 

According to what I have tested, it is not good to mix this add-in with separate installation of "Let's Encrypt" and "NGINX Home Assistant SSL proxy". These add-ons contain bugs in the GUI interface for configuration and can make the process of installing and configuring Nginx Proxy Manager unnecessarily complicated.
If I have a clean system and have not installed any of these add-ons, then the installation and configuration of Nginx Proxy Manager will go smoothly. Because it's a piece of work well done.

If it doesn't have any important configuration and data in the "Let's Encrypt" and "NGINX Home Assistant SSL proxy" settings, it's easiest to start over rather than trying to configure these things. And figure out where the error is.

As an example, I've given a configuration error that is generated directly by the "Let's Encrypt" plugin.  That's why I mentioned it.

I know this because I didn't " wander in here" as you say, but I've been working hard for a few days on getting a project up and running that includes this addon, among others.  When I was investigating how the configuration is transferred from configuration.yaml to the actual web server settings and why it doesn't work properly, I came up with a few procedures that can help to quickly solve the problem with the installation of these three mentioned plugins.

I think this is better advice than you gave by saying that it is not supported on Ubuntu.
Yes it is nice to mention that officially the project is not supported on Ubuntu. It's good to say that. But I believe the person has some reason why he is using Ubuntu and running it in the docker. that he doesn't want to just give up. Although this belongs in the community forum already.  Surely this is not some bug in this "addon".
Nor is it a thing that you, as a developer, could fix.

If I mentioned you in a previous comment, it was mainly to thank you for your work on the plugin. It's one of the few things in Home Assistant that just works.
I don't expect you to address why someone can't run it on Ubuntu.

**Comment by frenck** [comment]
> What I claim and insist,that is the easiest way in such a case ( and I have tried it), is to remove the addon, install MariaDB, check if it is running and then reinstall the addon.
> It's 100% tried and tested.

Removing the add-on is completely unneeded and unnecessary. You missed the point.

> If I mix addon and plug-in it's a translation error. Take it up with whoever translates the thing into czech. Can you describe what you understand by what term.

Add-on != Plugin. Those are different things.


> I think this is better advice than you gave by saying that it is not supported on Ubuntu.

Your comments have absolutely nothing to do with this issue report. Absolutely **NOTHING** in your comments provides a fix for the original issue reported here and is not related to anything in the issue report.

That said; Ubuntu is not supported by the Home Assistant project. Not much an add-on can change about that.

>  It's good to say that. But I believe the person has some reason why he is using Ubuntu and running it in the docker. 

He possibly has, in that case it becomes his problem; not ours. They run something unsupported. That is fine, but not our concern.

>  When I was investigating how the configuration is transferred from configuration.yaml to the actual web server settings and why it doesn't work properly, 

The `configuration.yaml` file has absolutely nothing to do with this add-on or project.
