### ISSUE TITLE
Authorization doesn't work

### ISSUE THREAD

**Issue by sergentum** [hassio-addons/addon-nginx-proxy-manager#388]
# Problem/Motivation

I'm trying to protect my services from internet with authorization but it doesn't work for some services. I have few docker services: emby, paperless-ngx, portainer - all configured as proxy by nginx manager and set all of them to be private. When I hit the url emby, paperless, portainer don't ask basic auth like it's not enabled at all. 

## Expected behavior

auth window pop up

## Actual behavior

auth window dont't pop up 

## Steps to reproduce

Play with those services in docker and try to protect them by nginx manager:
emby, paperless-ngx, portainer

## Proposed changes

no idea, nginx logs are not exposed in the UI, I think it could be usefull just for the beginning

**Comment by michaelblight** [comment]
I'm getting the same problem with version 0.12.3. If I take a working proxy host and set an access list, when I navigate to the url it immediately returns 403 forbidden, rather than prompting for the basic auth set up in the access list.

I think this is partly because the addon seems to need a restart after this type of change. However, once I do this I get "this site can't be reached" (ERR_HTTP2_PROTOCOL_ERROR) after shift-refresh on the client. This is likely to be not fully understanding the options. In the access list I have "allow all" and have tried both on and off for "satisfy any" and "pass auth to client". Still no login prompt.
