### ISSUE TITLE
Can't connect to the addon UI using Cloudflare certificates

### ISSUE THREAD

**Issue by VivantSenior** [hassio-addons/addon-nginx-proxy-manager#58]
# Problem

> I can't force the addon to work with Cloudflare domain and Origin certificate. The UI works via the local IP.

## Expected behavior

> Ability to connect the Nginx Proxy Manager via HTTPS using Cloudflare Origin certificates.

## Actual behavior

> HTTP Error 525 SSL handshake failed
![image](https://user-images.githubusercontent.com/49829548/71114334-d98c0300-21cf-11ea-9aa3-f0689d614bf5.png)

## Steps to reproduce

> Just use certificate / private key from Cloudflare with HTTPS [ports](https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy) accepted by Cloudflare, e.g. 2053.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by y0ast** [comment]
This works for me, using `Full (strict)` mode on cloudflare side.

**Comment by VivantSenior** [comment]
I tried `Full (strict)` but still can't access my instance of Nginx Proxy Manager.

Any ideas which settings on the Cloudflare site could interrupt the connection to the Proxy Manager?

**Comment by y0ast** [comment]
Hmm, I use port 443, did you?

I did nothing special, worked out of the box. It works fine if you turn off the cloudflare proxy?

**Comment by VivantSenior** [comment]
I'm using Nginx Proxy Manager in my Home Assistant instance ([an addon](https://github.com/hassio-addons/addon-nginx-proxy-manager) to the Home Assistant as a docker container). I available have three ports to configure:

| Description | Container internal port | External port | Error | Error description | Error description when Cloudflare disabled |
| --- | --- | --- | --- | --- | --- |
| HTTP Entrance port | 80 | 2052 | Only HTTPS traffic is allowed via Cloudflare | N/A | N/A |
| HTTPS/SSL Entrance port | 443 | 8443 | Error 526: Invalid SSL certificate | The origin web server does not have a valid SSL certificate. | NET::ERR_CERT_AUTHORITY_INVALID |
| Proxy management web interface | 81 | 2096 | Error 525: SSL handshake failed | Cloudflare is unable to establish an SSL connection to the origin server. | ERR_SSL_PROTOCOL_ERROR |

External ports are taken from [this post](https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy) (they are allowed by Cloudflare).

Which port should I use in order to connect to the NPM instance?

**Comment by Xyroqs** [comment]
In the router you need to add port sharing from the home assistant/hassio 8123 port to 443 or set CloudFlare SSL/TLS to Flexible and enable port sharing (in router) home assistant/hassio 8123 port to 80

**Comment by Xyroqs** [comment]
In the router you need to add port sharing from the home assistant/hassio 8123 port to 443 or set CloudFlare SSL/TLS to Flexible and enable port sharing (in router) home assistant/hassio 8123 port to 80 and set in CloudFlare "Always Use HTTPS" to On

**Comment by Xyroqs** [comment]
In the router you need to add port sharing from the homeassistant/hassio 8123 port to 443 or set CloudFlare SSL/TLS to Flexible and enable port sharing (in router) homeassistant/hassio 8123 port to 80 and set in CloudFlare "Always Use HTTPS" to On

**Comment by mdegat01** [comment]
@VivantSenior This issue is a bit old so you may have moved on but since its still marked as open I figured I'd add my 2 cents.  You don't actually need to expose a port for the Proxy Management Web Interface, you can actually use NPM itself to do that.  Just add a subdomain like `npm.<yourdomain>` and set NPM to forward traffic from that subdomain to port 81 of the internal IP you're running NPM on.  That way you can have literally everything to through NPM and keep the number of ports exposed to a bare minimum.

**Comment by frenck** [comment]
If you use cloudflare in front of stuff... why use this add-on in the first place? 🤷

**Comment by mdegat01** [comment]
Well cloudflare doesn't actually let you remap subdomains to ports like NPM does, you only provide an ip address for each subdomain. So without NPM as well adding subdomains is pretty pointless since you'd still have to put the port on the end for each url.

Plus then you'd have to expose all the ports on your router. And you'd have to enable ssl for each thing individually and upload the origin cert for each. Also only NPM let's you set the advanced nginx flags so there's a number of steps that are only possible with NPM in between cloudflare and HA/add-on like setting up [authenticated origin pulls](https://support.cloudflare.com/hc/en-us/articles/204899617).

Using these two in tandem is definitely better then either by itself in my opinion.
