### ISSUE TITLE
[::]:80 failed (97: Address family not supported by protocol)

### ISSUE THREAD

**Issue by poudenes** [hassio-addons/addon-nginx-proxy-manager#95]
Hi All,

I installed the latest Nginx Proxy Manager, Current version: 0.6.0
When I start I see this in the log:
```
2020/05/31 19:53:03 [emerg] 538#538: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
[19:53:04] INFO: Starting NGinx...
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2020/05/31 19:53:04 [emerg] 574#574: socket() [::]:80 failed (97: Address family not supported by protocol)
```
I can't access the webGui at all.

I saw a solution, tried but when I start Add-On again all changes are gone:

https://github.com/jc21/nginx-proxy-manager/issues/312

**Comment by frenck** [comment]
Ok, to solve this I need to expose a configuration setting to the NGINX Proxy Manager to allow one to turn this features on/off.

Going to add that.

**Comment by poudenes** [comment]
Thanks for the fast upcoming fix!

**Comment by frenck** [comment]
Looked at this, realized this is already handled by the add-on:

https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/8e46ede800b9a62310f56f2d42e7792b7300fb44/proxy-manager/rootfs/etc/services.d/manager/run#L19-L20

The error thrown, are by NGINX. Since the latest NGINX Proxy Manager brings in new templates, my current guess is that your current hosts are generated using previous templates in an older add-on version?

What you could try to do is make a change to a host, to ensure those hosts configuration files are re-generated using the latest templates by the upstream NGINX Proxy Manager project.

**Comment by poudenes** [comment]
I did remove the old NGINX Proxy Manager project because of a problem with not reroute correct when you have 2 https lines. It was always shown HA frontend

Maybe the hosts are stored somewhere?

And this have nothing to do with the External and Internal URL of HA right because its running itself in a docker?

Sorry for the silly questions...

**Comment by frenck** [comment]
The hosts are stored inside the add-on storage space. On removal of the add-on this is cleared.

configuration of Home Assistant itself has nothing to do with the templates or functionality of this add-on.

**Comment by poudenes** [comment]
Ok. I did remove the Add-On, then reinstalled it. No changes on config and I get the error as well
