### ISSUE TITLE
Access List not working as expected

### ISSUE THREAD

**Issue by moverperfect** [hassio-addons/addon-nginx-proxy-manager#99]
# Problem/Motivation

Access list "access" does not seem to be working in the way I expected it would

## Expected behavior

I created an access list that is "satisfy any", has no users and has one rule "allow 192.168.1.0/24". When attaching this to a proxy host, I expected this to only allow internal clients to have access and block all other requests. I expected this to work the same as adding this to the advanced section of the proxy host:
satisfy any;
allow 192.168.1.0/24;
deny all;

## Actual behavior

The access list instead blocks all traffic from all locations. I have to use the advanced section on all my proxy hosts

## Steps to reproduce

Create proxy host
Create access list as above
Try to access the site - shouldn't work
Remove the access list
Add in the advanced config
Try to access the site - should work

**Comment by sinclairpaul** [comment]
Looks to be an upstream issue that is resolved in a newer release, will need to wait for an addon update.

**Comment by colonelmattyman** [comment]
I am unable to get Basic Auth to work at all and it might be related to this.
In the access list I've:
- enabled "Satisfy any"
- added a username and password
- left the access tab as default

I've then attached this access list to the Proxy Host and saved it.
It doesn't prompt for username and password and just goes straight into the web page without authorising.

I've disabled and re-enabled the proxy host which hasn't helped and even restarted the container.

**Comment by frenck** [comment]
These are upstream issues. Please report them to the NGINX proxy manager project.
Add-ons wrap existing applications, in this case, the NGINX Proxy Manager.

Thanks 👍

**Comment by colonelmattyman** [comment]
@frenck I would have reported it there but it looks like the HA add-on isn't the most up to date version (release notes state it's 2.3.0 while the latest version is 2.4.0 as of 6 August). I don't want to be THAT guy that posts an issue and doesn't have the latest update installed.  :)

**Comment by frenck** [comment]
In that case, there is nothing left to do besides waiting.

**Comment by colonelmattyman** [comment]
@frenck Sorry. I deleted the post that you replied to while you were replying to it because I said that Home Assistant didn't have the latest version but it actually does, I just misread the release notes. My bad.

I have looked at the issues on Github for Proxy Manager and 2.4.0 has some pretty big security concerns for those of us using Custom SSL certificates with Basic Authentication.

Do you know if there is a way to force the plugin back to one of the previous versions of PM which didn't have this issue? 

https://github.com/jc21/nginx-proxy-manager/issues/148
